baseURL = "https://vicugna-pacos.github.io/"
languageCode = "en-us"
title = "アルパカのメモ"
theme = "suri"
hasCJKLanguages = true

[params]
  github = "vicugna-pacos"
  author = "alpaca"
  avatar = "/images/avatar.jpg"
  bio = "おおむねSIerにいますが、他業種の社内SEだったこともあります。"

[markup]
  [markup.highlight]
    style = "monokailight"
