baseURL = "https://vicugna-pacos.github.io/"
languageCode = "ja-jp"
title = "アルパカのメモ"
hasCJKLanguage = true
summaryLength = 100
theme = "suri"

GoogleAnalytics = "UA-143399608-2"

[params]
  github = "vicugna-pacos"
  author = "alpaca"
  avatar = "/images/avatar.jpg"
  bio = "おおむねSIerにいますが、他業種の社内SEだったこともあります。"

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
